version: '3'
services:
    mysql-server:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "53306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
