package io.github.iwag.jerseystarter.models;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/*
 * If you deal with a class as JAXB, following parts are important at least.
 * If you want to output with JSON, add "org.glassfish.jersey.media" into dependencies
 */

@XmlRootElement // important
public class Task {
    private String id;
    private String description;
    private Integer priority;
    @XmlElement(name = "until_date")
    private String untilDate;

    public Task(String id, String description, Integer priority, String untilDate) {
        this.id = id;
        this.description = description;
        this.priority = priority;
        this.untilDate = untilDate;
    }

    public Task() { // important
    }

    // all fields' setter and getter are necessary
    // Getters, setters, equals, hashCode and toString are generated by IDEA IntelliJ
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getUntilDate() {
        return untilDate;
    }

    public void setUntilDate(String untilDate) {
        this.untilDate = untilDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Task task = (Task) o;

        if (description != null ? !description.equals(task.description) : task.description != null) return false;
        if (priority != null ? !priority.equals(task.priority) : task.priority != null) return false;
        return untilDate != null ? untilDate.equals(task.untilDate) : task.untilDate == null;
    }

    @Override
    public int hashCode() {
        int result = description != null ? description.hashCode() : 0;
        result = 31 * result + (priority != null ? priority.hashCode() : 0);
        result = 31 * result + (untilDate != null ? untilDate.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Task{" +
                "description='" + description + '\'' +
                ", priority=" + priority +
                ", untilDate='" + untilDate + '\'' +
                '}';
    }
}
